pipeline{
agent any

parametes{

    string(name:'SPEC'dafaultvalue:"cypress/e2e/**/**",description:"Enter the scripts path that you want to execute")
    choice(name:'BROWSER',choices:['chrome','firefox','edgr'],description:"Choose the browser")
}

stages{
    stage('Build'{
        echo "Building the application"
    })
    stage('Testing'){
        steps{
            bat "npm i"
            bat "npx cypress run --browser ${BROWSER} --spec${SPEC}"
        
        }
 
 
    }
stage('Deploy'){
    echo "Deploy the application"
}



}
post{
    always{
        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, icon: '', keepAll: true, reportDir: 'cypress/report', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: '', useWrapperFileDirectly: true])
    }
}



}